### ISSUE TITLE
Tracking issue: highlighting improvements / tweaks

### ISSUE THREAD

**Issue by smjonas** [smjonas/live-command.nvim#4]
There are probably a million ways the highlighting algorithm can be improved.
Here are some examples:

**In progress**
- [ ] input: `oneword`, output: `hey`, expected highlights: a single replacement highlight created by joining multiple highlights, any deletions should be removed. This would involve detecting word boundaries. Status: in progress, see #8.

**Planned**
- [ ] input: `foo`, output: `o`, expected highlights: a single replacement highlight (the suffix `o` should not have been truncated) 

**Completed**
- [X] input `timestamp, _ := strconv.Atoi(line[0])`, output: `timestamp = strconv.Atoi(line[0]),`, check highlights! Fixed in f713c59.

**Comment by smjonas** [comment]
No longer an important issue at the moment.
